logging:
  level: INFO
  loggers:
    WhatToDo: DEBUG
  appenders:
    - type: file
      currentLogFilename: ./log/what-to-do.log
      threshold: ALL
      queueSize: 512
      discardingThreshold: 0
      archive: true
      archivedLogFilenamePattern: ./log/what-to-do-%d.log
      archivedFileCount: 5
      logFormat: "%-5p [%d{ISO8601,UTC+02:00}] %c: %m%n%rEx"
      bufferSize: 8KiB
      immediateFlush: true
    - type: console

database:
  driverClass: org.postgresql.Driver
  user: postgres
  password: password
  url: jdbc:postgresql://postgres/whattodo
  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  maxWaitForConnection: 1s
  validationQuery: "/* MyApplication Health Check */ SELECT 1"
  minSize: 8
  maxSize: 32
  checkConnectionWhileIdle: false

healthCheckPath: http://localhost:8080/todos
healthCheckToken: Bearer test-token
authToken: test-token