version: "3.3"
services:
  postgres:
    image: "postgres:latest"
    expose:
      - 5432
    volumes:
      - "postgres:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=whattodo
  whattodo-app:
    build:
      context: .
    ports:
      - "8080:8080"
volumes:
  postgres:
